# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxibot', '0005_carhistory_taxicallhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carhistory',
            name='car_time',
        ),
    ]
