# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxibot', '0006_remove_carhistory_car_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carhistory',
            name='taxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxibot.TaxiCallHistory'),
        ),
    ]
