# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxibot', '0007_auto_20170308_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxicallhistory',
            name='status',
            field=models.CharField(default='new', max_length=30),
        ),
    ]
